### ISSUE TITLE
[BUG] Flowlogs not created for flag based configuration

### ISSUE THREAD

**Issue by ml019** [hamlet-io/engine-plugin-aws#224]
## Expected Behaviour
While deprecated, creation of flowlogs for a vpc should still honour the boolean flags on the segment/environment/solution objects. 

## Current Behaviour
While the code appears to be in place, the creation logic only works on explicitly created `FlowLogs` entries.

## Possible Solution
Create a pseudo entry is the flags indicate flowlogs are rerquired.

## Steps to Reproduce

1. For ORMSS, E7, run `seg -u baseline`
2. Resulting template does not contain flowlog configuration.

## Your Environment
* CMDB Version used: v2.0.1
* Blueprint:

**Comment by roleyfoley** [comment]
Since the flow log configuration is now part of the network component the flow logs won't be created as part of the baseline component. I don't think they ever were as flow logs required a VPC 

With the recent changes in flow logs they can now be configured as the user requires so I'm not sure we can honour the layer level settings to enable flow logs. 

I'd suggest that we handle this through a Deployment Profile where VPC flow logs are required and remove the layer level configuration which enables and disables flow logs
