### ISSUE TITLE
Question: About handling of Enabled=False in volumemount

### ISSUE THREAD

**Issue by ken9ross** [hamlet-io/engine-plugin-aws#338]
It appears that if a mount is defined in masterdata.json as Enabled=false
```
            "ECS": {
                "Volumes" : {
                    "docker" : {
                        "Device" : "/dev/xvdcz",
                        "Size" : 50
                    },
                    "dockerVolume" : {
                        "Enabled" : false,
                        "Device" : "/dev/xvdv",
                        "Size" : "50",
                        "MountPath" : "/var/lib/docker/volumes"
                    }
                }
            },
```
The volume `dockerVolume` is still created using AWS::EC2::VolumeAttachment but not mounted to `/var/lib/docker/volumes`

Is that correct? What is the purpose of doing that?

**Comment by roleyfoley** [comment]
The AWS::EC2::VolumeAttachment  resource is only invoked when there is a DataVolume in use instead of the SystemVolumes provided by the Storage profile. VolumeAttachments allow us to have an volume that is independent to the instance itself so that if you delete or recreate the instance the volume data isn't lost. 

The SystemVolumes are attached to the instance as part of the instance provisioning and each instance gets its  own set of System Volumes. These are removed as the instance comes and goes. 

So the AWS::EC2::VolumeAttachment  shouldn't be created for the volumes that you've specified in the ticket. 

---

However on review of the implementation I found a couple of bugs that meant that when you specify a SystemVolume with `enabled: false` the enabled state is ignored and the volume will be included in the BlockDevices. 

The PR's referenced on this ticket will fix this issue and also provide another fix for making the Schema of volumes fixed with better feedback on what is required.
